import Starfield from "@/components/Bg";
import Footer from "@/components/Footer";
import Logo from "@/components/Logo";
import Navbar from "@/components/Navbar";
import Socials from "@/components/Socials";
import { DialogProvider } from "@/context/DialogContext";
import { QuestionProvider } from "@/context/QuestionContext";
import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "@/app/global.css";

const exo = Exo_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/logo-icon.png" />
        <title>Nimblic</title>
      </head>
      <body
        className={`max-w-screen flex min-h-screen flex-col justify-center gap-24 text-sm antialiased ${exo.className}`}
      >
        <DialogProvider>
          <QuestionProvider>
            <Navbar />
            <div className="absolute left-[15%] top-6 h-20 w-20 -translate-x-1/2 transform sm:left-[12.5%] sm:h-28 sm:w-28 xl:left-[20%]">
              <Logo />
            </div>
            <main className="max-w-screen flex h-[55%] flex-col sm:min-h-screen">{children}</main>
            <Footer />
            <Starfield />
            <Socials />
          </QuestionProvider>
        </DialogProvider>
        <NextTopLoader showSpinner={false} easing="ease" />
      </body>
    </html>
  );
}
